services:
  php-app:
    build: .
    container_name: hola-mundo-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    restart: unless-stopped
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html